networks:
  lbxnet:
    external: true   # docker network create lbxnet (one-time)

services:
  lbx-exporter:
    build:
      context: .
      dockerfile: playwright.dockerfile
    env_file: .env
    volumes:
      - ./data:/data
    networks: [lbxnet]

  lbx-loader:
    build:
      context: .
      dockerfile: loader.dockerfile
    env_file: .env
    volumes:
      - ./data:/data
    networks: [lbxnet]

  lbx-justwatch:
    build:
      context: .
      dockerfile: justwatch.dockerfile
    env_file: .env               # reuses your DB + JW_* settings
    networks: [lbxnet]
    restart: "no"                # run-once job; call it when you want
    # optional: if you want logs or shared files, uncomment:
    # volumes:
    #   - ./data:/data
    # optional: tweak batch and sleep without editing code:
    # environment:
    #   - JW_BATCH_SIZE=500
    #   - JW_RECHECK_DAYS=7
    #   - JW_SLEEP_S=0.8
