version: "3.9"

networks:
  lbxnet:
    external: true   # create once with: docker network create lbxnet

services:
  lbx-exporter:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    env_file: .env
    volumes:
      - ./data:/data         # /data/exports and /data/state live here
    networks: [lbxnet]

  lbx-loader:
    build:
      context: .
      dockerfile: Dockerfile.loader
    env_file: .env
    volumes:
      - ./data:/data
    networks: [lbxnet]
